AUTHOR = 'Ben Gras'
OUTPUT_PATH = '/usr/local/www/data/vhosts/www.shrike-systems.com'
PATH = 'content'
SITEURL = 'http://www.shrike-systems.com'
SITENAME = 'Shrike Systems'
TIMEZONE = 'CET'
THEME = '../pelican-themes/zurb-F5-basic'
GOOGLE_ANALYTICS = 'UA-50092958-1'
